services:
  interval-timer-api:
    environment:
      - DB_DATABASE=interval_app
      - DB_HOST=mysql-container
      - DB_PASSWORD=password
      - DB_PORT=3306
      - DB_USER=root

    image: fabo95/general:interval-timer-api
    container_name: interval-timer-api-container
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - mysql-network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
    ports:
      - 8081:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - mysql-network

  adminer:
    image: adminer:latest
    container_name: adminer-container
    ports:
      - 8082:8080
    networks:
      - mysql-network

networks:
  mysql-network:

volumes:
  db-data:
    driver: local
