services:
  frontend:
    image: node:18-alpine
    volumes:
      - ./:/home/fabi
    command: "npm run dev --prefix /home/fabi"
    depends_on:
      - mysql
    ports:
      - 3000:3000
    networks:
      - mysql-network


  mysql:
    image: mysql:latest
    container_name: mysql-container
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 8081:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - mysql-network

  adminer:
    image: adminer:latest
    container_name: adminer-container
    ports:
      - 8082:8080
    networks:
      - mysql-network
networks:
  mysql-network:

