name: App Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  next-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        file_name: .env.local
        fail_on_empty: false

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build frontend.
      run: npm run build

    - name: Upload Next build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: next-build-artifact
        path: |
          .next
          public
        retention-days: 7

  docker-push:
    needs: next-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Next build artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: next-build-artifact
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          # Sets the build context to the same location in which the app.Dockerfile lives and let us COPY (in app.Dockerfile) from this location.
          # Hint: app.Dockerfile must be inside the repository.
          # See: https://github.com/marketplace/actions/build-and-push-docker-images#customizing
          context: .
          push: true
          tags: fabo95/general
          file: ./app.Dockerfile





      
    
    
