name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build frontend.
      run: | 
        npm install
        npm run build
      
    
    
