name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  next-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build frontend.
      run: npm run build

    - name: Upload Next build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: next-build-artifact
        path: |
          .next
          public
        retention-days: 7

  docker-push:
    needs: next-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Next build artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: next-build-artifact

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: fabo95/general
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}





      
    
    
